name: euses-env
channels:
    - conda-forge
dependencies:
    - calliope=0.6.6.post1
    - gdal=2.4.1
    - pip
    - pip:
        - datapackage==1.15.1
        - geopy==2.0.0
        - numpy==1.19.1
        - openpyxl==3.0.6
        - spopt==0.1.0
        - rasterio==1.1.5
        - rasterstats==0.15.0
        - xlrd==1.2.0
